#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# (c) Copyright 2023 Sensirion AG, Switzerland
#
#     THIS FILE IS AUTOMATICALLY GENERATED!
#
# Generator:     sensirion-driver-generator 0.23.0
# Product:       sfx6xxx
# Model-Version: 2.0.0
#
 
import time
import argparse
from sensirion_shdlc_driver import ShdlcSerialPort
from sensirion_shdlc_driver.errors import ShdlcDeviceError
from sensirion_driver_adapters.shdlc_adapter.shdlc_channel import ShdlcChannel
from device import Sfx6xxxDevice
from commands import StatusCode

parser = argparse.ArgumentParser()
parser.add_argument('--serial-port', '-p', default='COM8')
args = parser.parse_args()

with ShdlcSerialPort(port=args.serial_port, baudrate=115200) as port:
    channel = ShdlcChannel(port)
    sensor = Sfx6xxxDevice(channel)
    time.sleep(2.0)
    serial_number = sensor.get_serial_number()
    print(f"serial_number: {serial_number}; ")
    curr_setpoint = sensor.get_setpoint()
    print(f"curr_setpoint: {curr_setpoint}; ")
    averaged_measured_value = sensor.read_averaged_measured_value(50)
    print(f"averaged_measured_value: {averaged_measured_value}; ")