import os

# Default paths
ROOT_DIRECTORY = os.path.dirname(os.path.abspath(__file__)) 
COMPUTER_USER_DIRECTORY = "hidden..."
PARTICULARS_ANALYSIS_DIRECTORY = "hidden..."
CAMPAIGN_MEASUREMENT_DIRECTORY = "hidden..."
REFERENCE_UIRAD_DIODE_DIRECTORY = os.path.join(CAMPAIGN_MEASUREMENT_DIRECTORY, "300um_UIRAD_Reference")
HIGH_FLUENCE_NEUTRONS_DIRECTORY = os.path.join(CAMPAIGN_MEASUREMENT_DIRECTORY, "High_Fluence_neutrons_2023")
LOW_FLUENCE_NEUTRONS_DIRECTORY = os.path.join(CAMPAIGN_MEASUREMENT_DIRECTORY, "low_fluence_neutrons_2025")
DOUBLE_IRR_NEUTRON_DIRECTORY = os.path.join(CAMPAIGN_MEASUREMENT_DIRECTORY, "Double_Irr_Neutron")
PROTON_CAMPAIGN_DIRECTORY = os.path.join(CAMPAIGN_MEASUREMENT_DIRECTORY, "Proton_Campaign")
BEAM_MONITOR_DIRECTORY = os.path.join(CAMPAIGN_MEASUREMENT_DIRECTORY, "Beam_Monitor")
LASER_CALIBRATION_DIRECTORY = os.path.join(CAMPAIGN_MEASUREMENT_DIRECTORY, "Laser_Calibration")

OSCILLOSCOPE_TIMEOUT = 10000 # ms

PELTIER_MAX_CURRENT = 5
PELTIER_MAX_VOLTAGE = 12

AIR_FLOW_SETPOINT_DEFAULT = 13

# Default voltage values for TCT
TCT_START_VOLTAGE = -900
TCT_STOP_VOLTAGE = -50
TCT_VOLTAGE_STEP_SIZE = 50

TCT_FINE_VOLTAGE_START = -300
TCT_FINE_VOLTAGE_STEP_SIZE = 25

# Default voltage values for IV/CV
IV_CV_START_VOLTAGE = -25
IV_CV_STOP_VOLTAGE = -900
IV_CV_VOLTAGE_STEP_SIZE = 25

CV_FINE_VOLTAGE_STOP = -250
CV_FINE_VOLTAGE_STEP_SIZE = 10

# Default keithley instrument settings IV/CV
COMPLIANCE_VALUE_DEFAULT = 100 # uA
IV_MEASURE_DELAY_DEFAULT = 10 # seconds
CV_MEASURE_DELAY_DEFAULT = 5 # seconds
SAMPLE_NUMBER_DEFAULT = 20 # number of samples
RAMPING_SPEED_DEFAULT = 5 # V/s

# Default LCR instrument settings
LCR_VOLTAGE_DEFAULT = 0.5 # V
LCR_FREQ_DEFAULT = 2 # kHz

# Default TCT Main panel values
TCT_TEMPERATURE_VALUES = "253"
LASER_NAME_DEFAULT = "Laser2692_"
USER_NAME_DEFAULT = " "

# Default TCT Laser tab
LASER_FREQ_DEFAULT = 1000 # Hz
LASER_STEP_SIZE_DEFAULT = 100 
LASER_PULSE_WIDTH_PERCENT_DEFAULT = 81.6 # %
LASER_MAX_STRENGTH = 3300 # mV
MOTOR_STAGES_SPEED_DEFAULT = 2000 # steps/s

# Default TCT Oscilloscope tab
WF_PER_VBIAS_DEFAULT = 200
POINTS_PER_WF_DEFAULT = 1250


OSCILLOSCOPEHSI = True

# Default TCT Voltage Source tab
VSOURCE_COMPLIANCE_DEFAULT = 100 # uA
if OSCILLOSCOPEHSI:
    VSOURCE_MEASURE_DELAY_DEFAULT = 8 # seconds
else:
    VSOURCE_MEASURE_DELAY_DEFAULT = 5 # seconds
VSOURCE_RAMPING_SPEED_DEFAULT = 5 # V/s
VSOURCE_RAMPING_INTERVAL_DEFAULT = 0.25 # s

# Default TCT Analysis tab
LOWER_INTEGRATION_LIMIT = 240
UPPER_INTEGRATION_LIMIT = 360

OSCILLOSCOPEHSI_IP = "" # Hidden

OSCILLOSCOPE_RECALL_DEFAULT = "TCT-latest.set"

OSCILLOSCOPEHSI_SUMMARY_FRAME = False

COPY_TEMPERATURE_FILES = True

RECORD_VOLTAGE_CURRENT_RAMPING_DATA = False