
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# (c) Copyright 2023 Sensirion AG, Switzerland
#
#     THIS FILE IS AUTOMATICALLY GENERATED!
#
# Generator:     sensirion-driver-generator 0.23.0
# Product:       sfx6xxx
# Model-Version: 2.0.0
#
import time
import argparse
from sensirion_shdlc_driver import ShdlcSerialPort
from sensirion_shdlc_driver.errors import ShdlcDeviceError
from sensirion_driver_adapters.shdlc_adapter.shdlc_channel import ShdlcChannel
from DAQ.AXIOM.TemperatureControl.sensirion_uart_sfx6xxx.device import Sfx6xxxDevice

 
class AirFluxControl:

    def __init__(self, port):
        """
        This constructor initializes the connection to the mass flow controller to read out the
        current flux and change the amount of air flowing into the setup.

        :param port: string; The name of the serial port to the SFC6000D.
        """
        self.port = port
        self.connected = False
        self.sensor = None
        self.serial_port = None

        
        # Connect air flow
        self.connect_air_flow()
        
    def connect_air_flow(self):
        # Connect air flow controller and set standard setpoint to 15 sl/min
        try:
                parser = argparse.ArgumentParser()
                parser.add_argument('--serial-port', '-p', default=self.port)
                args = parser.parse_args()
                # port = ShdlcSerialPort(port=args.serial_port, baudrate=115200)
                self.serial_port = ShdlcSerialPort(port=args.serial_port, baudrate=115200)
                # channel = ShdlcChannel(port)
                channel = ShdlcChannel(self.serial_port)
                self.sensor = Sfx6xxxDevice(channel)
                time.sleep(2.0)

                # Default air flow setpoint [sl/min].
                self.connected = True
                self.set_value(13)
        except Exception as e:
            self.connected = False
            print(f'Error: {e}')
            print('SFC600D is not connected! Continuing without air flow control.')
        
    def set_value(self, value):
        # Set air flow setpoint
        if self.connected:
            try:
                self.sensor.set_setpoint(value)
            except ShdlcDeviceError as e:
                print(f'Failed to set air flow setpoint: {e}')
            except Exception as e:
                print(f'An unexpected error occurred while setting air flow setpoint: {e}')
        else:
            print('Cannot set air flow setpoint: SFC600D is not connected.')
    
    def close(self):
        self.serial_port.close()
        
    def close_connection(self):
        # Properly close the serial connection
        if self.serial_port:
            try:
                self.serial_port.close()
                print("Serial port closed successfully.")
            except Exception as e:
                print(f"Error while closing the serial port: {e}")
            finally:
                self.serial_port = None
    
    def reconnect(self):
        # Reconnect air flow
        print("Attempting to reconnect...")
        self.close_connection()
        self.connect_air_flow()
        